[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.16", default-features = false }
bevy_replicon = "0.34.4"
serde = { version = "1.0", features = ["derive"] }
